# fly.toml app configuration
app = "telegram-fun-bot"
primary_region = "lhr"

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
